
project_id = "fbgeiasbtjfpqfqmllde"

[functions.process-booking-otp]
verify_jwt = false

[functions.validate-booking-otp]
verify_jwt = false

[functions.send-confirmation]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.bml-payment]
verify_jwt = false
