
# This file tells Netlify how to handle routes for single page applications
# All routes should be redirected to index.html for client-side routing to work

[build]
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
